2025-05-16 14:43:12,344 - __main__ - INFO - === EXTRAÇÃO DE ORDENS PENDENTES 2024-2025 ===
2025-05-16 14:43:12,344 - __main__ - INFO - Iniciando extração de ordens não finalizadas de 2024-2025
2025-05-16 14:43:12,344 - __main__ - INFO - e ordens recentes (últimos 7 dias)
2025-05-16 14:43:13,603 - __main__ - INFO - Database connection established.
2025-05-16 14:43:13,604 - __main__ - INFO - Total de lotes a processar: 12
2025-05-16 14:43:13,604 - __main__ - INFO - Buscando ordens não finalizadas de 2024-01-01 até 2025-05-16 e todas as ordens dos últimos 7 dias (2025-05-09 até 2025-05-16)
2025-05-16 14:43:13,604 - __main__ - INFO - Buscando ordens de 2024-01-01 a 2024-02-29...
2025-05-16 14:43:14,727 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 14:43:16,272 - __main__ - INFO - Fetched 78 orders. Processing...
2025-05-16 14:43:16,273 - __main__ - INFO - Total de 178 ordens encontradas para processamento.
2025-05-16 14:43:16,273 - __main__ - INFO - Das quais 178 são pendentes (não finalizadas).
2025-05-16 14:43:16,273 - __main__ - INFO - Processando lote de 50 ordens (1-50 de 178)...
2025-05-16 14:43:16,996 - __main__ - ERROR - Error processing Order ID 580409408: invalid input syntax for type integer: ""
LINE 11: ....0, 'iPhone 14 Pro max ', '', '', '', '', 0.0, 0.0, 0.0, '',
                                                                     ^

2025-05-16 14:43:17,155 - __main__ - ERROR - Error processing order 580409408: invalid input syntax for type integer: ""
LINE 11: ....0, 'iPhone 14 Pro max ', '', '', '', '', 0.0, 0.0, 0.0, '',
                                                                     ^

2025-05-16 14:43:18,229 - __main__ - ERROR - Error processing Order ID 580407369: invalid input syntax for type integer: ""
LINE 11: ...lho com marcas de uso tela quebrada', '', 0.0, 0.0, 0.0, '',
                                                                     ^

2025-05-16 14:43:18,388 - __main__ - ERROR - Error processing order 580407369: invalid input syntax for type integer: ""
LINE 11: ...lho com marcas de uso tela quebrada', '', 0.0, 0.0, 0.0, '',
                                                                     ^

2025-05-16 14:43:19,638 - __main__ - ERROR - Error processing Order ID 580407164: invalid input syntax for type integer: ""
LINE 11: ...hone 12 pró', '', '', 'senha 866252', '', 0.0, 0.0, 0.0, '',
                                                                     ^

2025-05-16 14:43:19,813 - __main__ - ERROR - Error processing order 580407164: invalid input syntax for type integer: ""
LINE 11: ...hone 12 pró', '', '', 'senha 866252', '', 0.0, 0.0, 0.0, '',
                                                                     ^

2025-05-16 14:43:20,957 - __main__ - ERROR - Error processing Order ID 580406985: invalid input syntax for type integer: ""
LINE 12: Senha: 185756', '', 0.0, 0.0, 0.0, '',
                                            ^

2025-05-16 14:43:21,119 - __main__ - ERROR - Error processing order 580406985: invalid input syntax for type integer: ""
LINE 12: Senha: 185756', '', 0.0, 0.0, 0.0, '',
                                            ^

2025-05-16 14:43:22,012 - __main__ - ERROR - Error processing Order ID 580406580: invalid input syntax for type integer: ""
LINE 12: Senha: 040520', '', 0.0, 0.0, 0.0, '',
                                            ^

2025-05-16 14:43:22,171 - __main__ - ERROR - Error processing order 580406580: invalid input syntax for type integer: ""
LINE 12: Senha: 040520', '', 0.0, 0.0, 0.0, '',
                                            ^

2025-05-16 14:43:23,129 - __main__ - ERROR - Error processing Order ID 580401372: invalid input syntax for type integer: ""
LINE 12: Checklist impossivel', '', 0.0, 0.0, 0.0, '',
                                                   ^

2025-05-16 14:43:23,291 - __main__ - ERROR - Error processing order 580401372: invalid input syntax for type integer: ""
LINE 12: Checklist impossivel', '', 0.0, 0.0, 0.0, '',
                                                   ^

2025-05-16 14:43:24,185 - __main__ - ERROR - Error processing Order ID 580400728: invalid input syntax for type integer: ""
LINE 13: (41) 995470052', '', 0.0, 0.0, 0.0, '',
                                             ^

2025-05-16 14:43:24,347 - __main__ - ERROR - Error processing order 580400728: invalid input syntax for type integer: ""
LINE 13: (41) 995470052', '', 0.0, 0.0, 0.0, '',
                                             ^

2025-05-16 14:43:25,561 - __main__ - ERROR - Error processing Order ID 580398153: invalid input syntax for type integer: ""
LINE 13: Senha: 171274', '', 0.0, 0.0, 0.0, '',
                                            ^

2025-05-16 14:43:25,720 - __main__ - ERROR - Error processing order 580398153: invalid input syntax for type integer: ""
LINE 13: Senha: 171274', '', 0.0, 0.0, 0.0, '',
                                            ^

2025-05-16 14:43:26,972 - __main__ - ERROR - Error processing Order ID 580397317: invalid input syntax for type integer: ""
LINE 13: Senha: 070804', '', 0.0, 0.0, 0.0, '',
                                            ^

2025-05-16 14:43:27,131 - __main__ - ERROR - Error processing order 580397317: invalid input syntax for type integer: ""
LINE 13: Senha: 070804', '', 0.0, 0.0, 0.0, '',
                                            ^

2025-05-16 14:43:28,337 - __main__ - ERROR - Error processing Order ID 580391273: invalid input syntax for type integer: ""
LINE 13: Senha: 153827', '', 0.0, 0.0, 0.0, '',
                                            ^

2025-05-16 14:43:28,495 - __main__ - ERROR - Error processing order 580391273: invalid input syntax for type integer: ""
LINE 13: Senha: 153827', '', 0.0, 0.0, 0.0, '',
                                            ^

2025-05-16 14:43:29,590 - __main__ - ERROR - Error processing Order ID 580390270: invalid input syntax for type integer: ""
LINE 12: Checklist Impossível ', '', 0.0, 0.0, 0.0, '',
                                                    ^

2025-05-16 14:43:29,752 - __main__ - ERROR - Error processing order 580390270: invalid input syntax for type integer: ""
LINE 12: Checklist Impossível ', '', 0.0, 0.0, 0.0, '',
                                                    ^

2025-05-16 14:43:31,176 - __main__ - ERROR - Error processing Order ID 580386810: invalid input syntax for type integer: ""
LINE 13: Senha: 070497', '', 0.0, 0.0, 0.0, '',
                                            ^

2025-05-16 14:43:31,335 - __main__ - ERROR - Error processing order 580386810: invalid input syntax for type integer: ""
LINE 13: Senha: 070497', '', 0.0, 0.0, 0.0, '',
                                            ^

2025-05-16 14:43:32,419 - __main__ - ERROR - Error processing Order ID 580386513: invalid input syntax for type integer: ""
LINE 12: Senha: 1159', '', 0.0, 0.0, 0.0, '',
                                          ^

2025-05-16 14:43:32,577 - __main__ - ERROR - Error processing order 580386513: invalid input syntax for type integer: ""
LINE 12: Senha: 1159', '', 0.0, 0.0, 0.0, '',
                                          ^

2025-05-16 14:43:33,450 - __main__ - ERROR - Error processing Order ID 580386485: invalid input syntax for type integer: ""
LINE 13: contato 4199274-7004', '', 0.0, 0.0, 0.0, '',
                                                   ^

2025-05-16 14:43:33,608 - __main__ - ERROR - Error processing order 580386485: invalid input syntax for type integer: ""
LINE 13: contato 4199274-7004', '', 0.0, 0.0, 0.0, '',
                                                   ^

2025-05-16 14:43:34,577 - __main__ - ERROR - Error processing Order ID 580385644: invalid input syntax for type integer: ""
LINE 14: Senha: 230191', '', 0.0, 0.0, 0.0, '',
                                            ^

2025-05-16 14:43:34,738 - __main__ - ERROR - Error processing order 580385644: invalid input syntax for type integer: ""
LINE 14: Senha: 230191', '', 0.0, 0.0, 0.0, '',
                                            ^

2025-05-16 14:43:35,849 - __main__ - ERROR - Error processing Order ID 580385298: invalid input syntax for type integer: ""
LINE 14: ', '', 0.0, 0.0, 0.0, '',
                               ^

2025-05-16 14:43:36,010 - __main__ - INFO - Extração concluída.
2025-05-16 14:45:56,486 - __main__ - INFO - === EXTRAÇÃO DE ORDENS PENDENTES 2024-2025 ===
2025-05-16 14:45:56,486 - __main__ - INFO - Iniciando extração de ordens não finalizadas de 2024-2025
2025-05-16 14:45:56,486 - __main__ - INFO - e ordens recentes (últimos 7 dias)
2025-05-16 14:45:57,763 - __main__ - INFO - Database connection established.
2025-05-16 14:45:57,764 - __main__ - INFO - Total de lotes a processar: 12
2025-05-16 14:45:57,764 - __main__ - INFO - Buscando ordens não finalizadas de 2024-01-01 até 2025-05-16 e todas as ordens dos últimos 7 dias (2025-05-09 até 2025-05-16)
2025-05-16 14:45:57,764 - __main__ - INFO - Buscando ordens de 2024-01-01 a 2024-02-29...
2025-05-16 14:45:58,302 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 14:46:00,114 - __main__ - INFO - Fetched 78 orders. Processing...
2025-05-16 14:46:00,114 - __main__ - INFO - Total de 178 ordens encontradas para processamento.
2025-05-16 14:46:00,115 - __main__ - INFO - Das quais 178 são pendentes (não finalizadas).
2025-05-16 14:46:00,115 - __main__ - INFO - Processando lote de 50 ordens (1-50 de 178)...
2025-05-16 14:47:06,169 - __main__ - INFO - Processando lote de 50 ordens (51-100 de 178)...
2025-05-16 14:48:09,888 - __main__ - INFO - Processando lote de 50 ordens (101-150 de 178)...
2025-05-16 14:49:14,583 - __main__ - INFO - Processando lote de 28 ordens (151-178 de 178)...
2025-05-16 14:49:52,234 - __main__ - INFO - Buscando ordens de 2024-03-01 a 2024-04-30...
2025-05-16 14:49:52,745 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 14:49:54,327 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 14:49:55,502 - __main__ - INFO - Fetched 26 orders. Processing...
2025-05-16 14:49:55,502 - __main__ - INFO - Total de 226 ordens encontradas para processamento.
2025-05-16 14:49:55,502 - __main__ - INFO - Das quais 226 são pendentes (não finalizadas).
2025-05-16 14:49:55,502 - __main__ - INFO - Processando lote de 50 ordens (1-50 de 226)...
2025-05-16 14:51:00,998 - __main__ - INFO - Processando lote de 50 ordens (51-100 de 226)...
2025-05-16 14:52:06,981 - __main__ - INFO - Processando lote de 50 ordens (101-150 de 226)...
2025-05-16 14:53:16,382 - __main__ - INFO - Processando lote de 50 ordens (151-200 de 226)...
2025-05-16 14:54:23,528 - __main__ - INFO - Processando lote de 26 ordens (201-226 de 226)...
2025-05-16 14:54:57,646 - __main__ - INFO - Buscando ordens de 2024-05-01 a 2024-06-30...
2025-05-16 14:54:58,119 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 14:54:59,577 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 14:55:01,296 - __main__ - INFO - Fetched 29 orders. Processing...
2025-05-16 14:55:01,296 - __main__ - INFO - Total de 229 ordens encontradas para processamento.
2025-05-16 14:55:01,297 - __main__ - INFO - Das quais 229 são pendentes (não finalizadas).
2025-05-16 14:55:01,297 - __main__ - INFO - Processando lote de 50 ordens (1-50 de 229)...
2025-05-16 14:56:07,566 - __main__ - INFO - Processando lote de 50 ordens (51-100 de 229)...
2025-05-16 14:56:54,111 - __main__ - ERROR - Error processing Order ID 580816290: could not convert string to float: '100%'
2025-05-16 14:56:54,114 - __main__ - ERROR - Error processing order 580816290: could not convert string to float: '100%'
2025-05-16 14:57:12,713 - __main__ - INFO - Processando lote de 50 ordens (101-150 de 229)...
2025-05-16 14:58:18,343 - __main__ - INFO - Processando lote de 50 ordens (151-200 de 229)...
2025-05-16 14:59:23,125 - __main__ - INFO - Processando lote de 29 ordens (201-229 de 229)...
2025-05-16 15:00:02,446 - __main__ - INFO - Buscando ordens de 2024-07-01 a 2024-08-31...
2025-05-16 15:00:02,879 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 15:00:03,892 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 15:00:05,082 - __main__ - INFO - Fetched 97 orders. Processing...
2025-05-16 15:00:05,083 - __main__ - INFO - Total de 297 ordens encontradas para processamento.
2025-05-16 15:00:05,083 - __main__ - INFO - Das quais 297 são pendentes (não finalizadas).
2025-05-16 15:00:05,083 - __main__ - INFO - Processando lote de 50 ordens (1-50 de 297)...
2025-05-16 15:01:10,756 - __main__ - INFO - Processando lote de 50 ordens (51-100 de 297)...
2025-05-16 15:01:48,102 - __main__ - ERROR - Error processing Order ID 581168439: could not convert string to float: '100%'
2025-05-16 15:01:48,104 - __main__ - ERROR - Error processing order 581168439: could not convert string to float: '100%'
2025-05-16 15:02:15,890 - __main__ - INFO - Processando lote de 50 ordens (101-150 de 297)...
2025-05-16 15:02:51,082 - __main__ - ERROR - Error processing Order ID 581120407: could not convert string to float: '100%'
2025-05-16 15:02:51,083 - __main__ - ERROR - Error processing order 581120407: could not convert string to float: '100%'
2025-05-16 15:02:52,962 - __main__ - ERROR - Error processing Order ID 581116302: could not convert string to float: '100%'
2025-05-16 15:02:52,963 - __main__ - ERROR - Error processing order 581116302: could not convert string to float: '100%'
2025-05-16 15:03:20,341 - __main__ - INFO - Processando lote de 50 ordens (151-200 de 297)...
2025-05-16 15:04:24,550 - __main__ - INFO - Processando lote de 50 ordens (201-250 de 297)...
2025-05-16 15:05:31,179 - __main__ - INFO - Processando lote de 47 ordens (251-297 de 297)...
2025-05-16 15:06:33,023 - __main__ - INFO - Buscando ordens de 2024-09-01 a 2024-10-31...
2025-05-16 15:06:33,544 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 15:06:34,640 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 15:06:36,351 - __main__ - INFO - Fetched 70 orders. Processing...
2025-05-16 15:06:36,351 - __main__ - INFO - Total de 270 ordens encontradas para processamento.
2025-05-16 15:06:36,351 - __main__ - INFO - Das quais 270 são pendentes (não finalizadas).
2025-05-16 15:06:36,351 - __main__ - INFO - Processando lote de 50 ordens (1-50 de 270)...
2025-05-16 15:07:45,079 - __main__ - INFO - Processando lote de 50 ordens (51-100 de 270)...
2025-05-16 15:08:51,107 - __main__ - INFO - Processando lote de 50 ordens (101-150 de 270)...
2025-05-16 15:09:57,115 - __main__ - INFO - Processando lote de 50 ordens (151-200 de 270)...
2025-05-16 15:11:00,139 - __main__ - INFO - Processando lote de 50 ordens (201-250 de 270)...
2025-05-16 15:12:04,395 - __main__ - INFO - Processando lote de 20 ordens (251-270 de 270)...
2025-05-16 15:12:31,785 - __main__ - INFO - Buscando ordens de 2024-11-01 a 2024-12-31...
2025-05-16 15:12:32,183 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 15:12:33,152 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 15:12:34,848 - __main__ - INFO - Fetched 56 orders. Processing...
2025-05-16 15:12:34,849 - __main__ - INFO - Total de 256 ordens encontradas para processamento.
2025-05-16 15:12:34,849 - __main__ - INFO - Das quais 256 são pendentes (não finalizadas).
2025-05-16 15:12:34,849 - __main__ - INFO - Processando lote de 50 ordens (1-50 de 256)...
2025-05-16 15:13:38,570 - __main__ - INFO - Processando lote de 50 ordens (51-100 de 256)...
2025-05-16 15:14:46,522 - __main__ - INFO - Processando lote de 50 ordens (101-150 de 256)...
2025-05-16 15:15:47,519 - __main__ - ERROR - Unexpected error processing order 581797524: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-05-16 15:15:49,789 - __main__ - ERROR - Unexpected error processing order 581795394: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581795394 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7d10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:15:49,805 - __main__ - ERROR - Unexpected error processing order 581791802: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581791802 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057140>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:15:52,187 - __main__ - ERROR - Unexpected error processing order 581790936: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581790936 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b72f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:15:52,207 - __main__ - ERROR - Unexpected error processing order 581789036: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581789036 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057c20>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:15:52,234 - __main__ - ERROR - Unexpected error processing order 581788884: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581788884 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b49e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:15:52,254 - __main__ - ERROR - Unexpected error processing order 581788493: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581788493 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6090>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:15:54,816 - __main__ - ERROR - Unexpected error processing order 581787298: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581787298 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040579e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:06,475 - __main__ - ERROR - Unexpected error processing order 581778997: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581778997 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040553a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:06,486 - __main__ - ERROR - Unexpected error processing order 581778395: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581778395 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e5ac0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:06,504 - __main__ - ERROR - Unexpected error processing order 581773953: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581773953 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e7aa0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:06,537 - __main__ - ERROR - Unexpected error processing order 581773774: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581773774 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057d10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,286 - __main__ - ERROR - Unexpected error processing order 581768224: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581768224 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057530>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,308 - __main__ - ERROR - Unexpected error processing order 581765687: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581765687 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b77a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,321 - __main__ - ERROR - Unexpected error processing order 581765474: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581765474 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4dd0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,352 - __main__ - ERROR - Unexpected error processing order 581765457: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581765457 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7140>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,361 - __main__ - ERROR - Unexpected error processing order 581765197: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581765197 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e43b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,370 - __main__ - ERROR - Unexpected error processing order 581764493: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581764493 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e73e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,377 - __main__ - ERROR - Unexpected error processing order 581764199: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581764199 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057fe0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,396 - __main__ - ERROR - Unexpected error processing order 581764040: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581764040 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057e90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,418 - __main__ - ERROR - Unexpected error processing order 581762620: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581762620 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7740>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,450 - __main__ - ERROR - Unexpected error processing order 581762492: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581762492 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7d10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,470 - __main__ - ERROR - Unexpected error processing order 581761437: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581761437 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b76b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,486 - __main__ - ERROR - Unexpected error processing order 581761399: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581761399 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e6750>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,511 - __main__ - ERROR - Unexpected error processing order 581761160: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581761160 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b0770>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,554 - __main__ - ERROR - Unexpected error processing order 581756001: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581756001 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104055310>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,572 - __main__ - ERROR - Unexpected error processing order 581755938: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581755938 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1033f0740>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,599 - __main__ - ERROR - Unexpected error processing order 581755701: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581755701 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5f40>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,615 - __main__ - ERROR - Unexpected error processing order 581754580: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581754580 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b49b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:19,628 - __main__ - ERROR - Unexpected error processing order 581753610: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581753610 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7890>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:20,883 - __main__ - ERROR - Unexpected error processing order 581753058: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581753058 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4f80>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:20,902 - __main__ - ERROR - Unexpected error processing order 581751664: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581751664 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6ba0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:20,913 - __main__ - ERROR - Unexpected error processing order 581751025: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581751025 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5c10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:20,931 - __main__ - ERROR - Unexpected error processing order 581746976: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581746976 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b0890>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:22,156 - __main__ - INFO - Processando lote de 50 ordens (151-200 de 256)...
2025-05-16 15:16:22,175 - __main__ - ERROR - Unexpected error processing order 581746922: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581746922 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057f20>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:22,188 - __main__ - ERROR - Unexpected error processing order 581746315: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581746315 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040570b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:22,199 - __main__ - ERROR - Unexpected error processing order 581744415: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581744415 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104055ee0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:22,205 - __main__ - ERROR - Unexpected error processing order 581744374: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581744374 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057350>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:22,221 - __main__ - ERROR - Unexpected error processing order 581744025: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581744025 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b04d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:22,234 - __main__ - ERROR - Unexpected error processing order 581739783: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581739783 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b68a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:22,253 - __main__ - ERROR - Unexpected error processing order 581732580: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581732580 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7050>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:23,843 - __main__ - ERROR - Unexpected error processing order 581729709: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581729709 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7cb0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:23,865 - __main__ - ERROR - Unexpected error processing order 581729473: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581729473 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e6780>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:23,885 - __main__ - ERROR - Unexpected error processing order 581726948: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581726948 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7ad0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:23,892 - __main__ - ERROR - Unexpected error processing order 581726757: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581726757 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b77d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:23,909 - __main__ - ERROR - Unexpected error processing order 581726521: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581726521 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b02f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:23,919 - __main__ - ERROR - Unexpected error processing order 581725509: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581725509 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057e30>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:23,931 - __main__ - ERROR - Unexpected error processing order 581725500: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581725500 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104055d60>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:23,942 - __main__ - ERROR - Unexpected error processing order 581725437: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581725437 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040578c0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:23,960 - __main__ - ERROR - Unexpected error processing order 581725373: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581725373 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104055e50>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:23,980 - __main__ - ERROR - Unexpected error processing order 581722760: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581722760 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104056f60>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,000 - __main__ - ERROR - Unexpected error processing order 581718839: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581718839 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b3ad0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,027 - __main__ - ERROR - Unexpected error processing order 581718830: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581718830 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6d80>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,049 - __main__ - ERROR - Unexpected error processing order 581718521: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581718521 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7830>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,069 - __main__ - ERROR - Unexpected error processing order 581718480: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581718480 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6240>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,093 - __main__ - ERROR - Unexpected error processing order 581718470: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581718470 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e7080>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,107 - __main__ - ERROR - Unexpected error processing order 581718449: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581718449 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b66f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,115 - __main__ - ERROR - Unexpected error processing order 581718403: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581718403 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4ef0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,125 - __main__ - ERROR - Unexpected error processing order 581716903: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581716903 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b0e90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,142 - __main__ - ERROR - Unexpected error processing order 581715310: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581715310 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040568a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,152 - __main__ - ERROR - Unexpected error processing order 581713067: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581713067 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104056660>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,172 - __main__ - ERROR - Unexpected error processing order 581712954: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581712954 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e7890>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,189 - __main__ - ERROR - Unexpected error processing order 581712806: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581712806 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104054ec0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,212 - __main__ - ERROR - Unexpected error processing order 581709878: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581709878 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104056ab0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,226 - __main__ - ERROR - Unexpected error processing order 581709806: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581709806 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b04d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,235 - __main__ - ERROR - Unexpected error processing order 581709723: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581709723 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104080740>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:24,249 - __main__ - ERROR - Unexpected error processing order 581708146: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581708146 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6d20>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,283 - __main__ - ERROR - Unexpected error processing order 581707414: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581707414 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6db0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,297 - __main__ - ERROR - Unexpected error processing order 581707367: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581707367 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1029a2e40>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,328 - __main__ - ERROR - Unexpected error processing order 581707168: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581707168 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7530>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,355 - __main__ - ERROR - Unexpected error processing order 581706934: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581706934 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104081cd0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,368 - __main__ - ERROR - Unexpected error processing order 581706197: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581706197 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b0ad0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,401 - __main__ - ERROR - Unexpected error processing order 581699303: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581699303 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057890>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,431 - __main__ - ERROR - Unexpected error processing order 581698592: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581698592 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057a70>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,469 - __main__ - ERROR - Unexpected error processing order 581698429: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581698429 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e5160>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,479 - __main__ - ERROR - Unexpected error processing order 581697462: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581697462 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040574d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,501 - __main__ - ERROR - Unexpected error processing order 581696780: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581696780 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040579e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,524 - __main__ - ERROR - Unexpected error processing order 581696748: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581696748 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b3ad0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,544 - __main__ - ERROR - Unexpected error processing order 581693278: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581693278 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040805f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,562 - __main__ - ERROR - Unexpected error processing order 581693092: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581693092 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7530>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,572 - __main__ - ERROR - Unexpected error processing order 581692636: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581692636 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7920>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:25,600 - __main__ - ERROR - Unexpected error processing order 581692499: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581692499 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5310>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,321 - __main__ - INFO - Processando lote de 50 ordens (201-250 de 256)...
2025-05-16 15:16:27,343 - __main__ - ERROR - Unexpected error processing order 581692477: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581692477 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7e60>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,365 - __main__ - ERROR - Unexpected error processing order 581692433: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581692433 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040802f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,386 - __main__ - ERROR - Unexpected error processing order 581692327: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581692327 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b3a10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,405 - __main__ - ERROR - Unexpected error processing order 581691977: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581691977 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040553a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,417 - __main__ - ERROR - Unexpected error processing order 581691706: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581691706 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040570b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,433 - __main__ - ERROR - Unexpected error processing order 581691641: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581691641 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e4890>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,462 - __main__ - ERROR - Unexpected error processing order 581691634: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581691634 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104055dc0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,474 - __main__ - ERROR - Unexpected error processing order 581691255: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581691255 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057290>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,486 - __main__ - ERROR - Unexpected error processing order 581691062: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581691062 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b08c0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,514 - __main__ - ERROR - Unexpected error processing order 581690928: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581690928 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104080740>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,534 - __main__ - ERROR - Unexpected error processing order 581673660: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581673660 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6d80>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,557 - __main__ - ERROR - Unexpected error processing order 581667576: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581667576 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6690>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,568 - __main__ - ERROR - Unexpected error processing order 581666787: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581666787 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e4890>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,580 - __main__ - ERROR - Unexpected error processing order 581660136: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581660136 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057aa0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,590 - __main__ - ERROR - Unexpected error processing order 581659934: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581659934 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104055d30>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,604 - __main__ - ERROR - Unexpected error processing order 581659378: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581659378 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b0590>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,622 - __main__ - ERROR - Unexpected error processing order 581655602: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581655602 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104080620>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,650 - __main__ - ERROR - Unexpected error processing order 581649563: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581649563 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4950>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,671 - __main__ - ERROR - Unexpected error processing order 581648591: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581648591 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b52b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,683 - __main__ - ERROR - Unexpected error processing order 581647616: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581647616 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b0260>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,695 - __main__ - ERROR - Unexpected error processing order 581647162: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581647162 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104080740>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:27,702 - __main__ - ERROR - Unexpected error processing order 581646733: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581646733 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057b90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:29,321 - __main__ - ERROR - Unexpected error processing order 581642854: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581642854 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6a50>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:29,346 - __main__ - ERROR - Unexpected error processing order 581642810: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581642810 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7fb0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:29,371 - __main__ - ERROR - Unexpected error processing order 581639840: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581639840 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4500>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:30,667 - __main__ - ERROR - Unexpected error processing order 581639170: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581639170 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104081a90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:30,692 - __main__ - ERROR - Unexpected error processing order 581639085: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581639085 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6210>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:30,724 - __main__ - ERROR - Unexpected error processing order 581639030: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581639030 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6510>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:30,756 - __main__ - ERROR - Unexpected error processing order 581634633: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581634633 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b63f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:30,789 - __main__ - ERROR - Unexpected error processing order 581634204: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581634204 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7d10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:30,812 - __main__ - ERROR - Unexpected error processing order 581632349: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581632349 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104087d10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:31,997 - __main__ - ERROR - Unexpected error processing order 581628311: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581628311 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b54c0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,019 - __main__ - ERROR - Unexpected error processing order 581625257: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581625257 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b72f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,039 - __main__ - ERROR - Unexpected error processing order 581625195: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581625195 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1023e3350>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,063 - __main__ - ERROR - Unexpected error processing order 581621551: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581621551 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057f50>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,080 - __main__ - ERROR - Unexpected error processing order 581620353: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581620353 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057ec0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,099 - __main__ - ERROR - Unexpected error processing order 581620266: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581620266 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057bc0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,134 - __main__ - ERROR - Unexpected error processing order 581620209: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581620209 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040553d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,205 - __main__ - ERROR - Unexpected error processing order 581614850: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581614850 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104056e70>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,268 - __main__ - ERROR - Unexpected error processing order 581607667: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581607667 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040803b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,309 - __main__ - ERROR - Unexpected error processing order 581607658: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581607658 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b52b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,333 - __main__ - ERROR - Unexpected error processing order 581607394: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581607394 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4620>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,371 - __main__ - ERROR - Unexpected error processing order 581606706: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581606706 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5f10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,397 - __main__ - ERROR - Unexpected error processing order 581606474: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581606474 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b02c0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,425 - __main__ - ERROR - Unexpected error processing order 581605771: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581605771 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6ff0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,450 - __main__ - ERROR - Unexpected error processing order 581604862: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581604862 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7c80>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:32,471 - __main__ - ERROR - Unexpected error processing order 581600120: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581600120 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040802f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:33,980 - __main__ - INFO - Processando lote de 6 ordens (251-256 de 256)...
2025-05-16 15:16:34,001 - __main__ - ERROR - Unexpected error processing order 581600022: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581600022 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104056a50>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:34,031 - __main__ - ERROR - Unexpected error processing order 581599447: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581599447 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104055cd0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:34,092 - __main__ - ERROR - Unexpected error processing order 581599427: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581599427 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b13d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:34,126 - __main__ - ERROR - Unexpected error processing order 581596981: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581596981 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057890>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:34,180 - __main__ - ERROR - Unexpected error processing order 581573486: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/581573486 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104056990>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:34,224 - __main__ - ERROR - Unexpected error processing order 580216649: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/580216649 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1036131a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:35,434 - __main__ - INFO - Buscando ordens de 2025-01-01 a 2025-01-31...
2025-05-16 15:16:35,480 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-01-01&dataFinalEmissao=2025-01-31&limit=100&offset=0 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4b00>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:39,524 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 15:16:40,727 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-01-01&dataFinalEmissao=2025-01-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10239bd10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:45,518 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-01-01&dataFinalEmissao=2025-01-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104056c90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:48,714 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-01-01&dataFinalEmissao=2025-01-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104056a20>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:52,532 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-01-01&dataFinalEmissao=2025-01-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b3ce0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:16:56,497 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-01-01&dataFinalEmissao=2025-01-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414c380>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:17:01,596 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-01-01&dataFinalEmissao=2025-01-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414cc20>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:17:04,204 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-01-01&dataFinalEmissao=2025-01-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104056900>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:17:10,325 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-01-01&dataFinalEmissao=2025-01-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057ad0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:17:17,842 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 15:17:19,761 - __main__ - INFO - Fetched 3 orders. Processing...
2025-05-16 15:17:19,761 - __main__ - INFO - Total de 203 ordens encontradas para processamento.
2025-05-16 15:17:19,761 - __main__ - INFO - Das quais 203 são pendentes (não finalizadas).
2025-05-16 15:17:19,761 - __main__ - INFO - Processando lote de 50 ordens (1-50 de 203)...
2025-05-16 15:18:25,791 - __main__ - INFO - Processando lote de 50 ordens (51-100 de 203)...
2025-05-16 15:19:29,425 - __main__ - INFO - Processando lote de 50 ordens (101-150 de 203)...
2025-05-16 15:20:33,494 - __main__ - INFO - Processando lote de 50 ordens (151-200 de 203)...
2025-05-16 15:21:39,107 - __main__ - INFO - Processando lote de 3 ordens (201-203 de 203)...
2025-05-16 15:21:45,369 - __main__ - INFO - Buscando ordens de 2025-02-01 a 2025-02-28...
2025-05-16 15:21:45,783 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 15:21:47,417 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 15:21:48,416 - __main__ - INFO - Fetched 1 orders. Processing...
2025-05-16 15:21:48,416 - __main__ - INFO - Total de 201 ordens encontradas para processamento.
2025-05-16 15:21:48,416 - __main__ - INFO - Das quais 201 são pendentes (não finalizadas).
2025-05-16 15:21:48,416 - __main__ - INFO - Processando lote de 50 ordens (1-50 de 201)...
2025-05-16 15:22:55,974 - __main__ - INFO - Processando lote de 50 ordens (51-100 de 201)...
2025-05-16 15:24:20,142 - __main__ - ERROR - Unexpected error processing order 582167422: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582167422 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414ee40>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:20,156 - __main__ - ERROR - Unexpected error processing order 582167392: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582167392 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414fc50>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:20,172 - __main__ - ERROR - Unexpected error processing order 582167227: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582167227 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104054e90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:20,195 - __main__ - ERROR - Unexpected error processing order 582166694: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582166694 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104056b40>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:21,759 - __main__ - INFO - Processando lote de 50 ordens (101-150 de 201)...
2025-05-16 15:24:21,838 - __main__ - ERROR - Unexpected error processing order 582166551: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582166551 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057dd0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:21,849 - __main__ - ERROR - Unexpected error processing order 582166319: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582166319 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414c290>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:21,860 - __main__ - ERROR - Unexpected error processing order 582166115: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582166115 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414c9e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:21,871 - __main__ - ERROR - Unexpected error processing order 582162240: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582162240 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1029a2e40>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:21,889 - __main__ - ERROR - Unexpected error processing order 582162170: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582162170 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6bd0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:21,900 - __main__ - ERROR - Unexpected error processing order 582161948: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582161948 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5640>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:41,022 - __main__ - ERROR - Unexpected error processing order 582161895: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-05-16 15:24:42,227 - __main__ - ERROR - Unexpected error processing order 582161785: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582161785 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x102727c20>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,354 - __main__ - ERROR - Unexpected error processing order 582160693: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582160693 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414e7b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,380 - __main__ - ERROR - Unexpected error processing order 582160452: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582160452 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5d60>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,401 - __main__ - ERROR - Unexpected error processing order 582160281: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582160281 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4da0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,415 - __main__ - ERROR - Unexpected error processing order 582156968: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582156968 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b62d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,424 - __main__ - ERROR - Unexpected error processing order 582156759: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582156759 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040850a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,436 - __main__ - ERROR - Unexpected error processing order 582156636: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582156636 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104084b90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,442 - __main__ - ERROR - Unexpected error processing order 582156094: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582156094 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4ce0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,449 - __main__ - ERROR - Unexpected error processing order 582156017: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582156017 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4500>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,462 - __main__ - ERROR - Unexpected error processing order 582155588: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582155588 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5e80>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,470 - __main__ - ERROR - Unexpected error processing order 582154451: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582154451 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6e70>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,477 - __main__ - ERROR - Unexpected error processing order 582154006: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582154006 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414c590>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,485 - __main__ - ERROR - Unexpected error processing order 582151059: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582151059 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086db0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,498 - __main__ - ERROR - Unexpected error processing order 582150085: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582150085 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414f260>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,512 - __main__ - ERROR - Unexpected error processing order 582150074: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582150074 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414e6f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,537 - __main__ - ERROR - Unexpected error processing order 582149906: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582149906 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5490>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,547 - __main__ - ERROR - Unexpected error processing order 582148642: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582148642 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5af0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:47,555 - __main__ - ERROR - Unexpected error processing order 582148472: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582148472 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7da0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:50,846 - __main__ - ERROR - Unexpected error processing order 582145358: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582145358 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414fe90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:50,864 - __main__ - ERROR - Unexpected error processing order 582141703: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582141703 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104084f50>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:50,886 - __main__ - ERROR - Unexpected error processing order 582139312: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582139312 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5520>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:50,911 - __main__ - ERROR - Unexpected error processing order 582137602: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582137602 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b63f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:50,943 - __main__ - ERROR - Unexpected error processing order 582137475: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582137475 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414fa10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:50,960 - __main__ - ERROR - Unexpected error processing order 582137469: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582137469 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414e750>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:50,979 - __main__ - ERROR - Unexpected error processing order 582135998: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582135998 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414e300>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:52,418 - __main__ - ERROR - Unexpected error processing order 582133871: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582133871 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104084b60>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:55,245 - __main__ - ERROR - Unexpected error processing order 582130912: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582130912 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5490>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:55,264 - __main__ - ERROR - Unexpected error processing order 582127294: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582127294 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414d7f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:55,289 - __main__ - ERROR - Unexpected error processing order 582126391: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582126391 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414c920>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:55,313 - __main__ - ERROR - Unexpected error processing order 582126344: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582126344 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414c830>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:55,337 - __main__ - ERROR - Unexpected error processing order 582125970: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582125970 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040875f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:55,347 - __main__ - ERROR - Unexpected error processing order 582125965: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582125965 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040871d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:55,371 - __main__ - ERROR - Unexpected error processing order 582125956: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582125956 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414c830>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:55,390 - __main__ - ERROR - Unexpected error processing order 582125846: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582125846 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414c590>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:55,408 - __main__ - ERROR - Unexpected error processing order 582125291: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582125291 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414f110>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:55,433 - __main__ - ERROR - Unexpected error processing order 582125173: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582125173 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6ab0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:55,445 - __main__ - ERROR - Unexpected error processing order 582124263: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582124263 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104087aa0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:55,459 - __main__ - ERROR - Unexpected error processing order 582124239: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582124239 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040854c0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:56,576 - __main__ - INFO - Processando lote de 50 ordens (151-200 de 201)...
2025-05-16 15:24:56,592 - __main__ - ERROR - Unexpected error processing order 582123816: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582123816 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040841d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:56,611 - __main__ - ERROR - Unexpected error processing order 582119587: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582119587 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414f620>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:56,632 - __main__ - ERROR - Unexpected error processing order 582119292: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582119292 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414fc50>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:56,651 - __main__ - ERROR - Unexpected error processing order 582119169: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582119169 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4b60>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:56,670 - __main__ - ERROR - Unexpected error processing order 582117415: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582117415 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4560>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:24:58,114 - __main__ - ERROR - Unexpected error processing order 582116555: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582116555 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b41d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:01,516 - __main__ - ERROR - Unexpected error processing order 582116283: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582116283 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040859a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:01,538 - __main__ - ERROR - Unexpected error processing order 582116101: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582116101 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5d60>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:01,634 - __main__ - ERROR - Unexpected error processing order 582115252: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582115252 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5940>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:01,682 - __main__ - ERROR - Unexpected error processing order 582114892: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582114892 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414c650>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:01,728 - __main__ - ERROR - Unexpected error processing order 582111868: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582111868 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414d790>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:01,766 - __main__ - ERROR - Unexpected error processing order 582111790: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582111790 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414c2c0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:01,807 - __main__ - ERROR - Unexpected error processing order 582111545: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582111545 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104087fe0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:01,848 - __main__ - ERROR - Unexpected error processing order 582111489: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582111489 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e6480>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:01,900 - __main__ - ERROR - Unexpected error processing order 582110334: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582110334 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414e4b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:01,923 - __main__ - ERROR - Unexpected error processing order 582109934: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582109934 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414ffb0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:01,987 - __main__ - ERROR - Unexpected error processing order 582109906: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582109906 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b44d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,042 - __main__ - ERROR - Unexpected error processing order 582106119: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582106119 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b64e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,096 - __main__ - ERROR - Unexpected error processing order 582105974: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582105974 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4950>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,145 - __main__ - ERROR - Unexpected error processing order 582105923: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582105923 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086090>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,202 - __main__ - ERROR - Unexpected error processing order 582105815: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582105815 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040871a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,246 - __main__ - ERROR - Unexpected error processing order 582104953: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582104953 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6690>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,287 - __main__ - ERROR - Unexpected error processing order 582104273: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582104273 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7cb0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,314 - __main__ - ERROR - Unexpected error processing order 582099387: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582099387 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414d670>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,338 - __main__ - ERROR - Unexpected error processing order 582099340: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582099340 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414d190>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,365 - __main__ - ERROR - Unexpected error processing order 582099319: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582099319 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414e750>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,383 - __main__ - ERROR - Unexpected error processing order 582098939: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582098939 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e5490>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,401 - __main__ - ERROR - Unexpected error processing order 582098909: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582098909 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414e300>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,417 - __main__ - ERROR - Unexpected error processing order 582098658: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582098658 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414d670>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,478 - __main__ - ERROR - Unexpected error processing order 582098300: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582098300 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7530>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,694 - __main__ - ERROR - Unexpected error processing order 582098029: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582098029 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5010>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,724 - __main__ - ERROR - Unexpected error processing order 582097904: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582097904 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104087050>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,754 - __main__ - ERROR - Unexpected error processing order 582097742: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582097742 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e4710>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,793 - __main__ - ERROR - Unexpected error processing order 582097572: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582097572 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414fd10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:02,812 - __main__ - ERROR - Unexpected error processing order 582097101: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582097101 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414d190>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:08,253 - __main__ - ERROR - Unexpected error processing order 582094595: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582094595 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6a80>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:08,291 - __main__ - ERROR - Unexpected error processing order 582093890: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582093890 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5850>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:08,322 - __main__ - ERROR - Unexpected error processing order 582093329: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582093329 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6000>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:08,356 - __main__ - ERROR - Unexpected error processing order 582093164: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582093164 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104084800>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:08,390 - __main__ - ERROR - Unexpected error processing order 582092400: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582092400 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104084f80>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:08,411 - __main__ - ERROR - Unexpected error processing order 582092191: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582092191 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b66f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:08,429 - __main__ - ERROR - Unexpected error processing order 582092169: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582092169 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7680>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:08,457 - __main__ - ERROR - Unexpected error processing order 582084720: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582084720 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1035d7920>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:08,470 - __main__ - ERROR - Unexpected error processing order 582084606: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582084606 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414d670>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:08,484 - __main__ - ERROR - Unexpected error processing order 582084304: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582084304 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104085430>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:08,499 - __main__ - ERROR - Unexpected error processing order 582084297: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582084297 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040859a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:09,789 - __main__ - INFO - Processando lote de 1 ordens (201-201 de 201)...
2025-05-16 15:25:09,812 - __main__ - ERROR - Unexpected error processing order 582084220: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582084220 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414d580>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:11,131 - __main__ - INFO - Buscando ordens de 2025-03-01 a 2025-03-31...
2025-05-16 15:25:11,149 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=0 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414ffb0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:15,752 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 15:25:16,370 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414d0d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:20,539 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1029a21b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:24,532 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104057ef0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:28,876 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b1700>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:31,883 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b21b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:36,668 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b12b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:38,821 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040572c0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:42,119 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414c110>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:46,489 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414ffb0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:50,501 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b2cc0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:54,677 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b1640>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:25:57,908 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b2d20>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:00,281 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104085af0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:04,314 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10414c050>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:08,871 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-03-01&dataFinalEmissao=2025-03-31&limit=100&offset=100 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040572f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:12,504 - __main__ - INFO - Fetched 63 orders. Processing...
2025-05-16 15:26:12,507 - __main__ - INFO - Total de 163 ordens encontradas para processamento.
2025-05-16 15:26:12,507 - __main__ - INFO - Das quais 163 são pendentes (não finalizadas).
2025-05-16 15:26:12,507 - __main__ - INFO - Processando lote de 50 ordens (1-50 de 163)...
2025-05-16 15:26:13,750 - __main__ - ERROR - Unexpected error processing order 582392032: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582392032 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104084440>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:13,768 - __main__ - ERROR - Unexpected error processing order 582391848: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582391848 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104087200>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:13,794 - __main__ - ERROR - Unexpected error processing order 582391141: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582391141 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104085e50>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:13,814 - __main__ - ERROR - Unexpected error processing order 582390548: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582390548 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e6390>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:13,829 - __main__ - ERROR - Unexpected error processing order 582390330: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582390330 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e46e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:13,859 - __main__ - ERROR - Unexpected error processing order 582390160: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582390160 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1036127e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:13,877 - __main__ - ERROR - Unexpected error processing order 582389943: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582389943 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104084290>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:13,886 - __main__ - ERROR - Unexpected error processing order 582389906: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582389906 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104085640>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:13,892 - __main__ - ERROR - Unexpected error processing order 582386115: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582386115 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104085a00>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:13,899 - __main__ - ERROR - Unexpected error processing order 582385840: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582385840 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104087a70>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:13,924 - __main__ - ERROR - Unexpected error processing order 582385750: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582385750 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e72f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:13,941 - __main__ - ERROR - Unexpected error processing order 582385743: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582385743 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e5850>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:13,959 - __main__ - ERROR - Unexpected error processing order 582385725: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582385725 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086f00>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:13,969 - __main__ - ERROR - Unexpected error processing order 582385718: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582385718 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086c90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:13,987 - __main__ - ERROR - Unexpected error processing order 582385700: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582385700 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104084410>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,010 - __main__ - ERROR - Unexpected error processing order 582385637: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582385637 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b0410>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,024 - __main__ - ERROR - Unexpected error processing order 582385631: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582385631 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e4cb0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,041 - __main__ - ERROR - Unexpected error processing order 582382795: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582382795 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e7e90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,050 - __main__ - ERROR - Unexpected error processing order 582382660: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582382660 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1027058e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,064 - __main__ - ERROR - Unexpected error processing order 582381880: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582381880 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086900>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,085 - __main__ - ERROR - Unexpected error processing order 582381449: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582381449 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040879e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,098 - __main__ - ERROR - Unexpected error processing order 582381089: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582381089 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104085a00>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,106 - __main__ - ERROR - Unexpected error processing order 582380252: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582380252 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086420>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,128 - __main__ - ERROR - Unexpected error processing order 582380203: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582380203 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e47d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,151 - __main__ - ERROR - Unexpected error processing order 582379760: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582379760 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e4260>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,165 - __main__ - ERROR - Unexpected error processing order 582377329: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582377329 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104084590>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,186 - __main__ - ERROR - Unexpected error processing order 582376553: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582376553 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104087500>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,207 - __main__ - ERROR - Unexpected error processing order 582376219: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582376219 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104085f40>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,227 - __main__ - ERROR - Unexpected error processing order 582375830: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582375830 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b0c50>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,233 - __main__ - ERROR - Unexpected error processing order 582367087: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582367087 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e60c0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,253 - __main__ - ERROR - Unexpected error processing order 582365788: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582365788 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e43b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,276 - __main__ - ERROR - Unexpected error processing order 582364391: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582364391 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1026b00b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,298 - __main__ - ERROR - Unexpected error processing order 582364105: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582364105 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086f90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,314 - __main__ - ERROR - Unexpected error processing order 582363573: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582363573 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086360>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:14,334 - __main__ - ERROR - Unexpected error processing order 582363520: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582363520 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086660>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:16,276 - __main__ - ERROR - Unexpected error processing order 582360322: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582360322 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104085070>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:16,294 - __main__ - ERROR - Unexpected error processing order 582356997: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582356997 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e4e00>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:16,311 - __main__ - ERROR - Unexpected error processing order 582356673: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582356673 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104081820>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:16,331 - __main__ - ERROR - Unexpected error processing order 582356666: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582356666 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086660>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:16,356 - __main__ - ERROR - Unexpected error processing order 582356601: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582356601 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040879e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:16,368 - __main__ - ERROR - Unexpected error processing order 582355612: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582355612 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1036127e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:16,382 - __main__ - ERROR - Unexpected error processing order 582355579: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582355579 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e5c10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:16,398 - __main__ - ERROR - Unexpected error processing order 582353975: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582353975 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6f90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:16,413 - __main__ - ERROR - Unexpected error processing order 582353891: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582353891 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104081640>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:16,434 - __main__ - ERROR - Unexpected error processing order 582351643: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582351643 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1029a21b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:16,453 - __main__ - ERROR - Unexpected error processing order 582350815: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582350815 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e6ba0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:16,469 - __main__ - ERROR - Unexpected error processing order 582350672: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582350672 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e4a40>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:16,480 - __main__ - ERROR - Unexpected error processing order 582349702: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582349702 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b0c50>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,050 - __main__ - INFO - Processando lote de 50 ordens (51-100 de 163)...
2025-05-16 15:26:18,073 - __main__ - ERROR - Unexpected error processing order 582347975: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582347975 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b1070>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,097 - __main__ - ERROR - Unexpected error processing order 582345057: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582345057 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104085670>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,113 - __main__ - ERROR - Unexpected error processing order 582344952: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582344952 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104087470>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,127 - __main__ - ERROR - Unexpected error processing order 582344783: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582344783 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b22a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,153 - __main__ - ERROR - Unexpected error processing order 582344761: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582344761 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e61e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,165 - __main__ - ERROR - Unexpected error processing order 582344693: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582344693 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e49e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,177 - __main__ - ERROR - Unexpected error processing order 582344587: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582344587 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e7e90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,189 - __main__ - ERROR - Unexpected error processing order 582337372: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582337372 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104087230>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,203 - __main__ - ERROR - Unexpected error processing order 582336856: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582336856 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104085850>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,217 - __main__ - ERROR - Unexpected error processing order 582335743: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582335743 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1027058e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,248 - __main__ - ERROR - Unexpected error processing order 582335374: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582335374 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e72f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,273 - __main__ - ERROR - Unexpected error processing order 582330335: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582330335 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e7890>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,286 - __main__ - ERROR - Unexpected error processing order 582330259: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582330259 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b1c40>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,301 - __main__ - ERROR - Unexpected error processing order 582329651: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582329651 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b3e90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,343 - __main__ - ERROR - Unexpected error processing order 582329497: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582329497 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104087fe0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,362 - __main__ - ERROR - Unexpected error processing order 582329465: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582329465 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104087f50>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,378 - __main__ - ERROR - Unexpected error processing order 582329453: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582329453 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b1c40>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,404 - __main__ - ERROR - Unexpected error processing order 582328960: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582328960 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e7710>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,503 - __main__ - ERROR - Unexpected error processing order 582326433: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582326433 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e79e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,514 - __main__ - ERROR - Unexpected error processing order 582325585: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582325585 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e7bc0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,524 - __main__ - ERROR - Unexpected error processing order 582325324: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582325324 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104087500>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,535 - __main__ - ERROR - Unexpected error processing order 582322033: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582322033 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104084a40>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,546 - __main__ - ERROR - Unexpected error processing order 582321887: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582321887 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104084560>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,569 - __main__ - ERROR - Unexpected error processing order 582320298: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582320298 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086ae0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,597 - __main__ - ERROR - Unexpected error processing order 582317146: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582317146 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e5fa0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,621 - __main__ - ERROR - Unexpected error processing order 582316988: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582316988 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e6570>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,636 - __main__ - ERROR - Unexpected error processing order 582316131: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582316131 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e4ef0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,651 - __main__ - ERROR - Unexpected error processing order 582315918: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582315918 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b03e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,675 - __main__ - ERROR - Unexpected error processing order 582315904: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582315904 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5190>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,705 - __main__ - ERROR - Unexpected error processing order 582315322: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582315322 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e6660>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,733 - __main__ - ERROR - Unexpected error processing order 582315232: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582315232 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e49e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,746 - __main__ - ERROR - Unexpected error processing order 582315046: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582315046 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e5010>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,771 - __main__ - ERROR - Unexpected error processing order 582315031: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582315031 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104084cb0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,790 - __main__ - ERROR - Unexpected error processing order 582314122: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582314122 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104085dc0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,808 - __main__ - ERROR - Unexpected error processing order 582313981: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582313981 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b62d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,832 - __main__ - ERROR - Unexpected error processing order 582309068: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582309068 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040871d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,855 - __main__ - ERROR - Unexpected error processing order 582309005: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582309005 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086b70>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,875 - __main__ - ERROR - Unexpected error processing order 582308851: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582308851 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e61b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,892 - __main__ - ERROR - Unexpected error processing order 582308834: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582308834 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e6b40>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,912 - __main__ - ERROR - Unexpected error processing order 582308829: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582308829 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e7bf0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,928 - __main__ - ERROR - Unexpected error processing order 582308815: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582308815 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b1430>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,944 - __main__ - ERROR - Unexpected error processing order 582308799: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582308799 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b40e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,953 - __main__ - ERROR - Unexpected error processing order 582308700: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582308700 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e4da0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,968 - __main__ - ERROR - Unexpected error processing order 582308628: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582308628 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e41d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,975 - __main__ - ERROR - Unexpected error processing order 582306491: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582306491 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e5c10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:18,995 - __main__ - ERROR - Unexpected error processing order 582306486: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582306486 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104084aa0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:19,005 - __main__ - ERROR - Unexpected error processing order 582302858: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582302858 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104085e50>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:19,019 - __main__ - ERROR - Unexpected error processing order 582301886: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582301886 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4a40>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:19,035 - __main__ - ERROR - Unexpected error processing order 582301855: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582301855 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5610>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:19,044 - __main__ - ERROR - Unexpected error processing order 582301509: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582301509 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040866f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,157 - __main__ - INFO - Processando lote de 50 ordens (101-150 de 163)...
2025-05-16 15:26:20,180 - __main__ - ERROR - Unexpected error processing order 582297924: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582297924 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104087fe0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,196 - __main__ - ERROR - Unexpected error processing order 582295716: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582295716 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e4920>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,218 - __main__ - ERROR - Unexpected error processing order 582295276: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582295276 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e70b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,234 - __main__ - ERROR - Unexpected error processing order 582294436: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582294436 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e62a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,266 - __main__ - ERROR - Unexpected error processing order 582292438: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582292438 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104083680>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,288 - __main__ - ERROR - Unexpected error processing order 582292170: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582292170 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e7dd0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,303 - __main__ - ERROR - Unexpected error processing order 582289197: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582289197 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e5610>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,318 - __main__ - ERROR - Unexpected error processing order 582289182: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582289182 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086ae0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,331 - __main__ - ERROR - Unexpected error processing order 582288672: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582288672 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086060>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,351 - __main__ - ERROR - Unexpected error processing order 582286556: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582286556 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5730>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,363 - __main__ - ERROR - Unexpected error processing order 582285979: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582285979 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4b90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,381 - __main__ - ERROR - Unexpected error processing order 582285471: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582285471 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b65a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,401 - __main__ - ERROR - Unexpected error processing order 582285214: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582285214 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040856a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,414 - __main__ - ERROR - Unexpected error processing order 582283999: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582283999 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104085130>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:20,435 - __main__ - ERROR - Unexpected error processing order 582283614: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582283614 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x103611250>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:23,637 - __main__ - ERROR - Unexpected error processing order 582282927: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582282927 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e71a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,577 - __main__ - ERROR - Unexpected error processing order 582279013: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582279013 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e7980>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,669 - __main__ - ERROR - Unexpected error processing order 582276272: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582276272 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e7980>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,685 - __main__ - ERROR - Unexpected error processing order 582275668: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582275668 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e5610>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,702 - __main__ - ERROR - Unexpected error processing order 582275645: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582275645 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086de0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,721 - __main__ - ERROR - Unexpected error processing order 582272558: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582272558 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104087ef0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,742 - __main__ - ERROR - Unexpected error processing order 582271791: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582271791 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1029a21b0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,762 - __main__ - ERROR - Unexpected error processing order 582271392: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582271392 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5100>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,784 - __main__ - ERROR - Unexpected error processing order 582271384: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582271384 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040837a0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,808 - __main__ - ERROR - Unexpected error processing order 582270822: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582270822 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10368ec60>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,831 - __main__ - ERROR - Unexpected error processing order 582270756: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582270756 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6690>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,855 - __main__ - ERROR - Unexpected error processing order 582270135: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582270135 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5640>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,871 - __main__ - ERROR - Unexpected error processing order 582269971: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582269971 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b1fa0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,890 - __main__ - ERROR - Unexpected error processing order 582269588: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582269588 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e4410>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,909 - __main__ - ERROR - Unexpected error processing order 582269545: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582269545 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e6db0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,936 - __main__ - ERROR - Unexpected error processing order 582269351: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582269351 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b0ec0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,960 - __main__ - ERROR - Unexpected error processing order 582264654: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582264654 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b2e10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,976 - __main__ - ERROR - Unexpected error processing order 582264459: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582264459 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6c90>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:29,993 - __main__ - ERROR - Unexpected error processing order 582264090: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582264090 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4860>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:30,012 - __main__ - ERROR - Unexpected error processing order 582262501: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582262501 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10248f9e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:30,038 - __main__ - ERROR - Unexpected error processing order 582261383: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582261383 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e42f0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:30,061 - __main__ - ERROR - Unexpected error processing order 582261316: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582261316 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104085df0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:30,085 - __main__ - ERROR - Unexpected error processing order 582260549: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582260549 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b59d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:30,109 - __main__ - ERROR - Unexpected error processing order 582260390: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582260390 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7140>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:30,130 - __main__ - ERROR - Unexpected error processing order 582260304: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582260304 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b4fb0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:30,150 - __main__ - ERROR - Unexpected error processing order 582259704: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582259704 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e40e0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:30,176 - __main__ - ERROR - Unexpected error processing order 582259271: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582259271 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e6b10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:30,189 - __main__ - ERROR - Unexpected error processing order 582255465: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582255465 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b0770>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:30,209 - __main__ - ERROR - Unexpected error processing order 582255163: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582255163 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b3470>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:30,225 - __main__ - ERROR - Unexpected error processing order 582255088: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582255088 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e7680>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:30,245 - __main__ - ERROR - Unexpected error processing order 582254485: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582254485 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e6390>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:30,262 - __main__ - ERROR - Unexpected error processing order 582253784: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582253784 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1023e3350>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:32,217 - __main__ - INFO - Processando lote de 13 ordens (151-163 de 163)...
2025-05-16 15:26:32,236 - __main__ - ERROR - Unexpected error processing order 582252083: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582252083 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6840>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:32,257 - __main__ - ERROR - Unexpected error processing order 582251163: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582251163 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6630>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:32,276 - __main__ - ERROR - Unexpected error processing order 582251128: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582251128 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040845c0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:32,293 - __main__ - ERROR - Unexpected error processing order 582251098: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582251098 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b6000>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:32,312 - __main__ - ERROR - Unexpected error processing order 582251031: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582251031 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b5f10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:32,322 - __main__ - ERROR - Unexpected error processing order 582250848: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582250848 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10239af30>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:32,346 - __main__ - ERROR - Unexpected error processing order 582250669: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582250669 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e5a00>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:32,362 - __main__ - ERROR - Unexpected error processing order 582249609: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582249609 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e4a10>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:32,373 - __main__ - ERROR - Unexpected error processing order 582248865: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582248865 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b0c50>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:32,384 - __main__ - ERROR - Unexpected error processing order 582248666: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582248666 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b0950>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:32,401 - __main__ - ERROR - Unexpected error processing order 582248295: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582248295 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e6570>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:32,418 - __main__ - ERROR - Unexpected error processing order 582248029: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582248029 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040e6600>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:32,426 - __main__ - ERROR - Unexpected error processing order 582247096: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico/582247096 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x10248eae0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:33,924 - __main__ - INFO - Buscando ordens de 2025-04-01 a 2025-04-30...
2025-05-16 15:26:33,949 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-04-01&dataFinalEmissao=2025-04-30&limit=100&offset=0 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b7710>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:38,553 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-04-01&dataFinalEmissao=2025-04-30&limit=100&offset=0 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x1040b59d0>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:41,934 - __main__ - ERROR - Error fetching order list: HTTPSConnectionPool(host='api.tiny.com.br', port=443): Max retries exceeded with url: /public-api/v3/ordem-servico?dataInicialEmissao=2025-04-01&dataFinalEmissao=2025-04-30&limit=100&offset=0 (Caused by NewConnectionError("<urllib3.connection.HTTPSConnection object at 0x104086d50>: Failed to establish a new connection: [Errno 49] Can't assign requested address"))
2025-05-16 15:26:50,250 - __main__ - INFO - Fetched 100 orders. Processing...
2025-05-16 15:26:51,451 - __main__ - INFO - Fetched 47 orders. Processing...
2025-05-16 15:26:51,452 - __main__ - INFO - Total de 147 ordens encontradas para processamento.
2025-05-16 15:26:51,452 - __main__ - INFO - Das quais 147 são pendentes (não finalizadas).
2025-05-16 15:26:51,453 - __main__ - INFO - Processando lote de 50 ordens (1-50 de 147)...
2025-05-16 15:27:56,082 - __main__ - INFO - Processando lote de 50 ordens (51-100 de 147)...
2025-05-16 15:29:02,521 - __main__ - INFO - Processando lote de 47 ordens (101-147 de 147)...
2025-05-16 15:30:04,315 - __main__ - INFO - Buscando ordens de 2025-05-01 a 2025-05-16...
2025-05-16 15:30:04,679 - __main__ - INFO - Fetched 56 orders. Processing...
2025-05-16 15:30:04,680 - __main__ - INFO - Total de 56 ordens encontradas para processamento.
2025-05-16 15:30:04,680 - __main__ - INFO - Das quais 56 são pendentes (não finalizadas).
2025-05-16 15:30:04,680 - __main__ - INFO - Processando lote de 50 ordens (1-50 de 56)...
2025-05-16 15:30:47,833 - __main__ - ERROR - Error processing Order ID 582562544: could not convert string to float: '15%'
2025-05-16 15:30:47,834 - __main__ - ERROR - Error processing order 582562544: could not convert string to float: '15%'
2025-05-16 15:31:10,458 - __main__ - INFO - Processando lote de 6 ordens (51-56 de 56)...
2025-05-16 15:31:20,557 - __main__ - INFO - Buscando ordens de 2025-05-09 a 2025-05-16...
2025-05-16 15:31:21,069 - __main__ - INFO - Fetched 29 orders. Processing...
2025-05-16 15:31:21,069 - __main__ - INFO - Total de 29 ordens encontradas para processamento.
2025-05-16 15:31:21,069 - __main__ - INFO - Das quais 29 são pendentes (não finalizadas).
2025-05-16 15:31:21,069 - __main__ - INFO - Processando lote de 29 ordens (1-29 de 29)...
2025-05-16 15:32:00,563 - __main__ - WARNING - Total de 394 ordens com falha no processamento.
2025-05-16 15:32:00,576 - __main__ - INFO - Ordens com falha salvas em falhas_extrac_2024_2025_pending.csv
2025-05-16 15:32:00,576 - __main__ - INFO - === RESUMO DA EXTRAÇÃO ===
2025-05-16 15:32:00,576 - __main__ - INFO - Total de ordens encontradas: 2255
2025-05-16 15:32:00,576 - __main__ - INFO - Ordens pendentes (não-finalizadas) de 2024-2025: 2226
2025-05-16 15:32:00,577 - __main__ - INFO - Ordens dos últimos 7 dias: 29
2025-05-16 15:32:00,577 - __main__ - INFO - Falhas de processamento: 394
2025-05-16 15:32:00,577 - __main__ - INFO - =========================
2025-05-16 15:32:00,584 - __main__ - INFO - Extração concluída.
